BACKEND_LOCAL_TARGET_BUILDED=$(GITHUB_WORKSPACE)/target
BACKEND_LOCAL_TARGET_DEPLOY=$(BACKEND_LOCAL_TARGET_BUILDED)
BACKEND_VERSION=$(GITHUB_SHA)

label-war: 
	cp $(BACKEND_LOCAL_TARGET_BUILDED)/chasqui.war $(BACKEND_LOCAL_TARGET_DEPLOY)/chasqui_$(BACKEND_VERSION).war;