BACKEND_LOCAL_TARGET_BUILDED=$(GITHUB_WORKSPACE)/target
BACKEND_LOCAL_TARGET_DEPLOY=$(BACKEND_LOCAL_TARGET_BUILDED)
BACKEND_VERSION=$(github.event.inputs.tags)

label-war: 
	cp $(BACKEND_LOCAL_TARGET_BUILDED)/chasqui.war $(BACKEND_LOCAL_TARGET_DEPLOY)/chasqui_$(BACKEND_VERSION).war;
	ls $(BACKEND_LOCAL_TARGET_DEPLOY);