# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build with Maven

on:
  push:
    branches: [ disabled ]
  pull_request:
    branches: [ disabled ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4
      with:
        maven-version: 3.3.9
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-        
    - name: Build with Maven
      run: mvn clean install -Dmaven.test.skip=true -T 1C --file pom.xml
    - name: label war
      run: make label-war
